AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket for static/media files

Resources:
  BookstoreS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bookstorebk
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      Tags:
        - Key: Name
          Value: bookstore-s3

Outputs:
  BookstoreS3Bucket:
    Value: !Ref BookstoreS3Bucket